### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [sarteleb/brandons_app_with_model#1]
Looking very nice! One weird thing I was able to do though is enter a negative number for number of pets, which I can't think of a use case for. Try using [this resource](http://stackoverflow.com/questions/4416278/how-to-implement-min-max-validator-in-rails-3) to make sure the number of pets is at least 0 or 1 (whichever makes the most sense to you).

**Comment by sarteleb** [comment]
Fixed :)

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
